version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - '*'
  - package-ecosystem: pip
    directory: /.github
    schedule:
      interval: weekly
    groups:
      python-ci:
        patterns:
          - '*'
  - package-ecosystem: pip
    directory: /.devcontainer
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directories:
      - /docker
      - /.devcontainer
    schedule:
      interval: weekly
  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: weekly
